### ISSUE TITLE
[Feature request] Convert sublime-snippet to sane-snippet

### ISSUE THREAD

**Issue by Kristinita** [idleberg/sublime-tinker-tools#1]
### 1. Request

It would be nice, if sublime-tinker-tools will support convert `sublime-snippet` to [**`sane-snippet`**](https://github.com/bobthecow/sublime-sane-snippets).

### 2. Justification

SaneSnippets more convenient for human readability, than default XML-based snippets. See [**example**](https://github.com/bobthecow/sublime-sane-snippets#sanesnippets-for-sublime-text-2) in SaneSnippets repository.

I have 20+ `sublime-snippet` files and I want quick convert them to `sane-snippet` format.

### 3. Expected behavior

For example, I run command in my terminal:

```shell
tinker-sane "*.sublime-snippet"
```

All files with extension `sublime-snippet` in current folder will convert to `sane-snippet`.

Thanks.

**Comment by idleberg** [comment]
I'd rather add support in my [atomizr](https://gist.github.com/idleberg/db6833ee026d2cd7c043bba36733b701) project, that's probably more appropriate. Thanks for suggesting!
